session.save_handler = files
session.save_path = "/var/lib/php/sessions"
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.auto_start = 1

output_buffering = 4096
